name: upload-release-to-tps
on:
  push:
    branches:
      - main

jobs:
  check-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Convert base64 to credentials.zip
        run: |
             base64 -d ${{ secrets.TPS_CREDENTIALS}} > credentials.zip
             md5sum credentials.zip

