name: upload-release-to-tps
on:
  push:
    branches:
      - release

jobs:
  check-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Download release
        uses: robinraju/release-downloader@v1.8
        with:
          latest: true
          fileName: "*.tar"
          tarBall: true
          out-file-path: "latest-release"
      - name: Retrieve TPS credentials
        uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secret: ${{ secrets.TPS_CREDENTIALS }}
          filename: "credentials.zip"
          is-executable: false
          working-directory: "./"
      - name: Push up to TPS
        shell: bash
        run:  |
              FILE_NAME=$(ls ./latest-release/torizon-core*.tar)
              mkdir ${GITHUB_WORKSPACE}/deploy
              mkdir ${GITHUB_WORKSPACE}/storage
              mkdir ${GITHUB_WORKSPACE}/workdir
              docker pull torizon/torizoncore-builder:3
              docker run --rm -v${GITHUB_WORKSPACE}/deploy:/deploy -v${GITHUB_WORKSPACE}:/workdir -v${GITHUB_WORKSPACE}/storage:/storage -v/var/run/docker.sock:/var/run/docker.sock --network=host torizon/torizoncore-builder:3 images unpack "${FILE_NAME}"
              docker run --rm -v${GITHUB_WORKSPACE}/deploy:/deploy -v${GITHUB_WORKSPACE}:/workdir -v${GITHUB_WORKSPACE}/storage:/storage -v/var/run/docker.sock:/var/run/docker.sock --network=host torizon/torizoncore-builder:3 platform push --credentials ./credentials.zip --package-name tps-cicd --package-version tps-cicd-1.0 base
