name: upload-release-to-tps
on:
  push:
    branches:
      - release

jobs:
  check-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Download release
        uses: robinraju/release-downloader@v1.8
        with:
          latest: true
          fileName: "tps_cicd*.tar"
          tarBall: true
          out-file-path: "latest-release"
      - name: Check release
        run:  ls -l ./latest-release
