name: upload-release-to-tps
on:
  push:
    branches:
      - main

jobs:
  check-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Convert base64 to credentials.zip
        uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secrets: ${{ secrets.TPS_CREDENTIALS}}
          filename: "credentials.zip"
          is-executable: false
          working-directory: "./"
      - name: Check credentials
        run:  |
              md5sum credentials.zip
              ls -l ./
              unzip credentials.zip

